FINANCE_KEYWORDS = [
    'acquisizione', 'ammortamento', 'antitrust', 'azienda', 'azione', 'banca', 'baratto', 'bilancio',
    'bolla', 'speculativa', 'broker', 'capitalismo', 'commercio', 'commodity', 'compensazione',
    'consensus', 'consob', 'contante', 'corporativismo', 'credito', 'delocalizzazione', 'delta',
    'demurrage', 'distributismo', 'domanda', 'econofisica', 'esportazione', 'esternalità',
    'fabbisogno', 'finanza', 'fiscalità', 'monetaria', 'flottante', 'frazionamento', 'azionario',
    'funzione', 'monetaria', 'fusione', 'gamma', 'globalizzazione',
    'greche', 'gettito', 'guadagno', 'inerzia', 'fiscale', 'inflazione', 'isocosto', 'isoquanto', 'kaizen',
    'kanban', 'kaufsystem', 'keiretsu', 'know', 'how', 'lavoro', 'leva', 'finanziaria', 'operativa', 'liberismo',
    'liquidità', 'logistica', 'macroeconomia', 'market', 'microeconomia', 'minusvalenza', 'mission',
    'moneta', 'negoziazione', 'nazionalizzazione', 'oligopolio', 'operations', 'pensione', 'pluslavoro',
    'plusvalore', 'plusvalenza', 'politica monetaria', 'prezzo', 'privatizzazione', 'profitto',
    'progresso', 'tecnico', 'qualità', 'rata', 'rating', 'regressione', 'resistenza', 'retribuzione',
    'rischio', 'risorse', 'risparmio', 'scala', 'sconto', 'signoraggio', 'sistema', 'produttivo',
    'socializzazione', 'sospensione', 'sottoscorta', 'spin', 'stagflazione', 'stakeholder', 'statalismo',
    'strumento', 'derivato', 'supporto', 'sussidiarietà', 'svalutazione', 'swap', 'swaption', 'tasso',
    'training', 'trend', 'trendline', 'utilità', 'ultrarendimento', 'valuta', 'vega', 'visione', 'volatilità',
    'warrant', 'debito', 'konten', 'aktion', 'anlagegut', 'kasse', 'konsolidierung', 'abdeckung', 'schuld',
    'finanziell', 'aussage', 'fließen', 'einkommen', 'darlehen', 'verlust', 'markt', 'prozentsatz', 'preis',
    'profitieren', 'bewertung', 'verhältnis', 'bedienung', 'lager', 'wert', 'comptes', 'atout', 'équilibre',
    'espèces', 'couverture', 'dette', 'financière', 'financier', 'déclaration', 'couler', 'brute', 'brut',
    'revenu', 'prêt', 'prête', 'perte', 'marché', 'pourcentage', 'prix', 'taux', 'rapport', 'téléscripteur',
    'valeur', 'accounts', 'action', 'asset', 'balance', 'cash', 'consolidation', 'coverage', 'credit', 'debt',
    'financial', 'statement', 'flow', 'gross', 'income', 'loan', 'loss', 'market', 'percentage', 'price',
    'profit', 'rate', 'ratio', 'service', 'stock', 'ticker', 'value'
]
